import React from "react";
import { useParams } from "react-router-dom";
import Navbar from "./Navbar";
import NSSFooter from "./NSSFooter";
import "./EventPage.css";

// Sample event data
const eventImages = {
  gram_sampark: [
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs1.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs2.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs3.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs4.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs5.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs6.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs7.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs8.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs9.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs10.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs11.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs12.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs13.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs14.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs15.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs16.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs17.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs18.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs19.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs20.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs21.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs22.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs23.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs24.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs25.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs26.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs27.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs28.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs29.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs30.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs31.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/gs32.jpg'
  ],
  drishtikon: [
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr1.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr2.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr3.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr4.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr5.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr6.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr7.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr8.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr9.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr10.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr11.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr12.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr13.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr14.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr15.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr16.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr17.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr18.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr19.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr20.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr21.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr22.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr23.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr24.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr25.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr26.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr27.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr28.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr29.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr30.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr31.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr32.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr33.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr34.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr35.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr36.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/dr37.jpg'
  ],
  chakrvyuh: [
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch1.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch2.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch3.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch4.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch5.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch6.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch7.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch8.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch9.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch10.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch11.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch12.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch13.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch14.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch15.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch16.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch17.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ch18.jpg'
  ],
  prayas: [
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr1.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr2.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr3.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr4.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr5.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr6.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr7.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr8.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr9.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr10.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr11.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr12.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr13.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr14.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr15.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr16.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr17.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr18.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr19.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr20.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr21.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr22.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr23.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr24.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr25.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr26.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr27.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr28.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr29.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr30.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr31.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr32.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr33.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr34.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr35.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr36.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr37.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr38.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr39.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr40.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr41.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr42.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr43.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr44.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr45.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr46.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr47.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr48.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr49.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr50.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr51.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr52.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/pr53.jpg'
  ],
  junoon: [
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju1.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju2.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju3.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju4.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju5.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju6.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju7.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju8.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju9.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju10.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju11.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju12.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju13.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju14.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju15.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju16.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju17.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju18.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju19.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju20.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju21.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju22.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju23.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju24.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju25.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju26.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju27.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju28.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju29.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju30.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju31.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju32.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ju33.jpg'
  ],
  naya_summit: [
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns1.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns2.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns3.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns4.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns5.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns6.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns7.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns8.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns9.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns10.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns11.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns12.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns13.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns14.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns15.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns16.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns17.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns18.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns19.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns20.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns21.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns22.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns23.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns24.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns25.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns26.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns27.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns28.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns29.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns30.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns31.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns32.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns33.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns34.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns35.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns36.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns37.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns38.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns39.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns40.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns41.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns42.jpg',
    'https://res.cloudinary.com/daxr191iv/image/upload/f_auto,q_auto/ns43.jpg'
  ]
};


const EventPage = () => {
  const { year, eventName } = useParams(); // Get params from URL

  return (
    <div>
      <Navbar />
      <div className="event-page">
        <h2>{eventName.toUpperCase()} - {year}</h2>
        <div className="event-gallery">
          {eventImages[eventName]?.map((img, index) => (
            <a key={index} href={img} target="_blank" rel="noopener noreferrer">
              <img src={img} alt={`Event ${eventName}`} className="event-image" />
            </a>
          ))}
        </div>
      </div>
      <NSSFooter />
    </div>
  );
};

export default EventPage;